# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartTriple',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word1', models.TextField()),
                ('word2', models.TextField()),
                ('word3', models.TextField()),
            ],
            options={
                'db_table': 'start_triple',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripleToWord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word1', models.TextField()),
                ('word2', models.TextField()),
                ('word3', models.TextField()),
                ('next_word', models.TextField()),
                ('frequency', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'triple_to_word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StartTripleManager',
            fields=[
                ('starttriple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markov.StartTriple')),
            ],
            bases=('markov.starttriple',),
        ),
        migrations.CreateModel(
            name='TripleToWordManager',
            fields=[
                ('tripletoword_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markov.TripleToWord')),
            ],
            bases=('markov.tripletoword',),
        ),
    ]
